---
apps:
  -
    app: &Application
      class: APIApplication
      file:  APIApplication.php
      middlewares: [ HTTPParser, ModPHP ]

servers:
  -
    protocol: HTTP
    socket: 'tcp://192.168.10.36:9996'
    min-children: 1
    max-children: 5
    app: *Application
    
  -
    protocol: HTTP
    socket: 'tcp://192.168.10.36:9997'
    min-children: 1
    max-children: 5
    app: *Application
          
  -
    protocol: HTTP
    socket: 'tcp://192.168.10.36:9998'
    min-children: 1
    max-children: 5
    app: *Application

