---
apps:
  -
    app: &Application
      class: Application
      file: Application.php
      middlewares: [HTTPParser]

servers:
  -
    protocol: HTTP
    socket: 'tcp://127.0.0.1:9998'
    min-children: 5
    max-children: 10
    app: *Application
  -
    protocol: SCGI
    socket: 'tcp://127.0.0.1:9999'
    min-children: 1
    max-children: 2
    app: *Application
